CREATE TABLE IF NOT EXISTS wallets (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    available_funds NUMERIC(24, 8) NOT NULL CHECK(available_funds >= 0),
    CONSTRAINT fk_user_id_wallets FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);