spring.application.name=trading-bot
binance.websocket.stream.url=wss://stream.binance.com:9443
binance.http.klines.url=https://testnet.binance.vision/api/v3/klines
binance.http.futures.url=https://fapi.binance.com/fapi/v1/
cyclic.http.time=60000


# KONFIGURACJA WĄTKÓW
spring.task.execution.thread-name-prefix=BotWorker-
# wątki działające cały czas w tle - dostępne
spring.task.execution.pool.core-size=4
# max liczba wątków, jeśli nagle przyjdzie gigantyczny ruch z giełdy
spring.task.execution.pool.max-size=10
# liczba zadań, które mogą czekać w kolejce, jeśli wszystkie 10 wątków jest zajętych
spring.task.execution.pool.queue-capacity=100

# POŁĄCZENIE Z BAZĄ DANYCH POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/trading_db
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true