spring.application.name=trading-bot
binance.websocket.stream.url=wss://stream.binance.com:9443
binance.http.url=https://testnet.binance.vision/api/v3/klines



# KONFIGURACJA WĄTKÓW
spring.task.execution.thread-name-prefix=BotWorker-
# wątki działające cały czas w tle - dostępne
spring.task.execution.pool.core-size=4
# max liczba wątków, jeśli nagle przyjdzie gigantyczny ruch z giełdy
spring.task.execution.pool.max-size=10
# liczba zadań, które mogą czekać w kolejce, jeśli wszystkie 10 wątków jest zajętych
spring.task.execution.pool.queue-capacity=100