spring.config.import=optional:file:.env[.properties]

spring.application.name=trading-bot
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{0} - %msg%n

# Binance tools
binance.websocket.stream.url=wss://stream.binance.com:9443
binance.http.futures.url=https://fapi.binance.com/fapi/v1/
binance.test.base.url=https://testnet.binance.vision
binance.path.klines=/api/v3/klines
binance.path.order=/api/v3/order
binance.path.balance=/api/v3/account
binance.api.secret=${Secret_Key}
binance.api.key=${API_KEY}

cyclic.http.time=60000


# KONFIGURACJA WĄTKÓW
spring.task.execution.thread-name-prefix=BotWorker-
# wątki działające cały czas w tle - dostępne
spring.task.execution.pool.core-size=4
# max liczba wątków, jeśli nagle przyjdzie gigantyczny ruch z giełdy
spring.task.execution.pool.max-size=10
# liczba zadań, które mogą czekać w kolejce, jeśli wszystkie 10 wątków jest zajętych
spring.task.execution.pool.queue-capacity=100

# POŁĄCZENIE Z BAZĄ DANYCH POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/trading_db
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true