spring.application.name=backend
# debug=true

spring.config.import=optional:file:.env[.properties]
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{0} - %msg%n

# POŁĄCZENIE Z BAZĄ DANYCH POSTGRESQL
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/trading_db
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# włączenie flyway do inicjalizacji bazy danych z plików .sql
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# logging.level.org.flywaydb=DEBUG
# spring.flyway.fail-on-missing-locations=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true